version: "3"

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    command: uvicorn main:app --reload

networks:
  default:
    external:
      name:
        network_rabbit
