version: "3"

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8001


  mongo:
    image: mongo
    restart: always
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password


networks:
  default:
    external:
      name:
        network_rabbit
